### ISSUE TITLE
Replicating the project

### ISSUE THREAD

**Issue by martinszy** [mozboz/fc-pagegen#3]
Hi, we're trying to replicate the project, and we're finding an error:

1) The readme says the spreadsheet is referenced by name, but it's actually by ID.
2) I get this error when I run: # python rundmc.py

```
Traceback (most recent call last):
  File "rundmc.py", line 15, in <module>
    activeLocations = getActiveLocationsFromMasterSheet(masterSheetKey, credentialsFileName)
  File "/var/www/fc-pagegen/firstContactSheets.py", line 24, in getActiveLocationsFromMasterSheet
    data = loadRangeFromSheet(sheetKey, "Locations", "A3:D100", credentialsFileName)
  File "/var/www/fc-pagegen/firstContactSheets.py", line 15, in loadRangeFromSheet
    wks = gc.open_by_key(sheetKey).worksheet(sheetTab)
  File "/var/www/fc-pagegen/venv/local/lib/python2.7/site-packages/gspread/client.py", line 178, in open_by_key
    raise SpreadsheetNotFound
```

**Comment by martinszy** [comment]
So, to answer myself, the spreadsheet needs to be shared with the new user I created in the google developer console, such as  xxx-xxx@developer.gserviceaccount.com

**Comment by mozboz** [comment]
Yep, it's not not found, it's just not available.

So you can setup your own test installation, I'll add you (via your gmail account) to a location where you can pull down a copy of a master list and 2 location sheets. If you then make a copy of all 3, and update the ID to the ID of your new master sheet, add your developer-user to that sheet, you should be able to get everything working. 

Please leave this issue open, so I have a reminder to fix the docs on this issue, and perhaps make the test/dev process a bit more easily replicable.

m
